name: Test
on: [push, pull_request]

env:
  NODE_VERSION: 12.x

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'pull_request' || (!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore NPM cache
        uses: actions/cache@v1
        continue-on-error: true
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run test